### ISSUE TITLE
Bot unable to detect Glyph of Disposal

### ISSUE THREAD

**Issue by flexagontnt** [gtw123/OpusSolver#5] opened 2019-02-09 19:19 UTC
I don't know why the bot won't do the puzzle "Embalming Fluid". An error says it can't identify a glyph.

**Comment by gtw123** [comment] 2019-02-10 04:59
Fixed now.

The problem is that the sidebar "fades out" at the bottom, and the fix I applied yesterday for small screens wasn't quite accounting for that.

**Closed as completed by gtw123** 2019-02-10 04:59 UTC

**Comment by 837951602** [comment] 2019-03-12 17:37
How does it matter? Bot can move unused atom far away
